export type AuthAccessState =
  | 'UNAUTHENTICATED'
  | 'AUTHENTICATING'
  | 'PROFILE_LOADING'
  | 'PROFILE_ERROR'
  | 'ACCESS_LOADING'
  | 'WORKSPACE_SELECT_REQUIRED'
  | 'WORKSPACE_ACCESS_CONFIRMED'
  | 'WORKSPACE_CONTEXT_LOADING'
  | 'WORKSPACE_CONTEXT_READY'
  | 'ACCESS_DENIED'
  | 'SESSION_REVOKED';

