export type AuthAccessState =
  | 'UNAUTHENTICATED'
  | 'AUTHENTICATING'
  | 'PROFILE_LOADING'
  | 'PROFILE_ERROR'
  | 'ACCESS_LOADING'
  | 'WORKSPACE_SELECT_REQUIRED'
  | 'WORKSPACE_ACCESS_CONFIRMED'
  | 'WORKSPACE_CONTEXT_LOADING'
  | 'WORKSPACE_CONTEXT_READY'
  | 'ACCESS_DENIED'
  | 'SESSION_REVOKED';

export interface WorkspaceDirectoryState {
  kind: 'DIRECTORY' | 'EMPTY';
  initialFilter?: 'all' | 'operational' | 'history';
  reason?: 'PROVISIONING_REQUIRED' | 'TENANT_HAS_NO_WORKSPACE' | 'NO_ACTIVE_ASSIGNMENT' | 'NO_ACCESSIBLE_WORKSPACE' | 'ACCESS_DENIED' | 'RESOLUTION_ERROR';
  canCreateTournament?: boolean;
}

